- hosts: webservers
  become: true
  gather_facts: true
  tasks:
    - name: updatecache
      apt:
        update_cache: yes
    - name: install pip
      become: true
      apt:
        name: python3-pip
        state: present
        update_cache: true
    - name: install flask
      pip: name=flask
- hosts: HAproxy
  become: true
  tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 7200
    - name: Installing the packages
      become: true
      apt:
        name: haproxy
        state: latest
    - name: upgrade packages
      apt:
        update_cache: 'yes'
        upgrade: dist
        force_apt_get: 'yes'

    - name: Gather facts from servers
      setup:
        filter: ansible_default_ipv4.address
    - name: Removing existing default_haproxy_cfg
      file:
        path: /etc/haproxy/haproxy.cfg
        state: absent
      notify:
        - restart Haproxy
    - name: deploy new haproxy configuration
      template:
        src: ./templates/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify:
        - restart Haproxy
      
  handlers:
    - name: restart Haproxy
      service:
        name: haproxy
        state: restarted
- hosts: webservers
  gather_facts: yes
  tasks:
    - name: read application
      copy: src=/etc/ansible/application2.py dest=./application2.py
    - name: start flask app
      shell: |
        export FLASK_APP=./application2.py
        export FLASK_RUN_HOST=0.0.0.0
        export FLASK_RUN_PORT=8080
        flask run&	

